# Server Configuration
server:
  host: "0.0.0.0"
  port: 8000
  title: "Interest Expand API"
  description: "API for generating more interests based on personas given interests"
  version: "1.1.0"

# LLM Configuration
llm:
  config_list:
    - model: "gpt-4o-mini"
  timeout: 120
  temperature: 0.1